version: '3.8'

services:
  node-api:
    build: .
    container_name: my-finances-node
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=finances
      - JWT_SECRET=superSecret
    command: sh -c "sleep 10 && node server.js"

  mysql:
    image: mysql:8.0
    container_name: my-finances-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finances
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-api:
    build: ../my-finances-python/data/flask-api
    container_name: my-finances-python
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: finances

volumes:
  mysql_data:
