version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=SenhaSQL#3
      - DB_NAME=finance_db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SenhaSQL#3
      MYSQL_DATABASE: finance_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
